TOKENS_TO_SKILLS = {
    'agile':'Agile Methodologies',
	'agile_methodologies':'Agile Methodologies',
	'agile_methodology':'Agile Methodologies',
	'ai':'Artificial Intelligence',
	'algorithms':'Algorithms',
	'amazon_s3':'Amazon S3',
	'amazon_web_services':'AWS',
	'analytical':'Analytical Skills',
	'analytical_skills':'Analytical Skills',
	'analytics':'Analytical Skills',
	'ansible':'DevOps',
	'apache_kafka':'Apache Kafka',
	'apache_spark':'Apache Spark',
	'api':'REST APIs',
	'apis':'REST APIs',
	'artificial_intelligence':'Artificial Intelligence',
	'aurora':'Databases',
	'automation':'DevOps',
	'aws':'AWS',
	'azure':'Microsoft Azure',
	'bi':'Business Intelligence',
	'big_data':'Big Data',
	'big_query':'Databases',
	'bigquery':'Big Data',
	'biquery':'Databases',
	'bitbucket':'Git',
	'business_intelligence':'Business Intelligence',
	'c#':'C#',
	'c++':'C++',
	'cakephp':'PHP',
	'ci':'DevOps',
	'ci cd':'DevOps',
	'cleansing':'Extract, Transform, Load (ETL)',
	'clojure':'Clojure',
	'CNN':'Machine Learning',
	'cobol':'Cobol',
	'communication_skills':'Communication',
	'communications':'Communication',
	'computer_science':'Computer Science',
	'containerisation':'Docker Products',
	'containerization':'Docker Products',
	'continuous_improvement':'Software Development',
	'continuous_integration':'DevOps',
	'dash':'Data Visualization',
	'data_mart':'Data Warehousing',
	'data_marts':'Data Warehousing',
	'data_model':'Data Modeling',
	'data_pipelines':'Streaming Data',
	'data_science':'Data Science',
	'data_structures':'Data Structures',
	'data_visualisation':'Data Visualization',
	'data_visualization':'Data Visualization',
	'data_warehouse':'Data Warehousing',
	'data_warehouses':'Data Warehousing',
	'data_warehousing':'Data Warehousing',
	'database':'Databases',
	'datadog':'Monitoring',
	'datamart':'Data Warehousing',
	'datamarts':'Data Warehousing',
	'db2':'Databases',
	'dba':'Databases',
	'dbms':'Databases',
	'deep_learning':'Deep Learning',
	'devops':'DevOps',
	'docker':'Docker Products',
	'docker_compose':'Docker Products',
	'dynamodb':'Databases',
	'ec2':'AWS',
	'english':'English',
	'english_language':'English',
	'etl':'Extract, Transform, Load (ETL)',
	'exasol':'Databases',
	'extract':'Extract, Transform, Load (ETL)',
	'extracting':'Extract, Transform, Load (ETL)',
	'extraction':'Extract, Transform, Load (ETL)',
	'extraction_transformation_and_loading':'Extract, Transform, Load (ETL)',
	'flink':'Flink',
	'flume':'Flume',
	'front_end':'Front-End Development',
	'front-end':'Front-End Development',
	'gcp':'Google Cloud Platform (GCP)',
	'git':'Git',
	'github':'Git',
	'gitlab':'Git',
	'go':'Go',
	'golang':'Go',
	'google':'Google Cloud Platform (GCP)',
	'gradle':'Gradle',
	'grafana':'Monitoring',
	'hadoop':'Hadoop',
	'hdfs_hive':'Hive',
	'hibernate':'Spring Framework',
	'hive':'Hive',
	'iac':'DevOps',
	'ibm_mainframe':'Mainframe',
	'informatica':'Informatica',
	'ingest':'Extract, Transform, Load (ETL)',
	'ingestion':'Extract, Transform, Load (ETL)',
	'java':'Java',
	'javascript':'JavaScript',
	'jenkins':'DevOps',
	'json':'REST APIs',
	'kafka':'Apache Kafka',
	'kanban':'Agile Methodologies',
	'Kanban':'Agile Methodologies',
	'keras':'Machine Learning',
	'kibana':'Monitoring',
	'kubernetes':'Cloud Technologies',
	'liguibase':'DevOps',
	'linux':'Linux',
	'loading':'Extract, Transform, Load (ETL)',
	'looker':'Google Cloud Platform (GCP)',
	'machine_learning':'Machine Learning',
	'microservices':'Microservices',
	'microsoft_azure':'Microsoft Azure',
	'microsoft_power_bi':'Microsoft Power BI',
	'microsoft_sql_server':'Microsoft SQL Server',
	'ml':'Machine Learning',
	'model':'Data Modeling',
	'modeling':'Data Modeling',
	'modelling':'Data Modeling',
	'models':'Data Modeling',
	'mongo':'Mongo DB',
	'mongod':'Mongo DB',
	'mongodb':'Mongo DB',
	'monitoring':'Monitoring',
	'ms_azure':'Microsoft Azure',
	'ms_power_bi':'Microsoft Power BI',
	'ms_sql_server':'Microsoft SQL Server',
	'mssql':'Microsoft SQL Server',
	'natural_language':'NLP',
	'natural_language_processing':'NLP',
	'neural_network':'Machine Learning',
	'nifi':'NiFi',
	'nlp':'NLP',
	'nltk':'NLP',
	'nosql':'NoSQL',
	'object_oriented_programming':'Object-Oriented Programming (OOP)',
	'object-oriented_programming':'Object-Oriented Programming (OOP)',
	'oop':'Object-Oriented Programming (OOP)',
	'oracle':'Oracle Databases',
	'php':'PHP',
	'pipeline':'Extract, Transform, Load (ETL)',
	'plotly':'Data Visualization',
	'posix':'Linux',
	'postgres':'PostgreSQL',
	'postgresql':'PostgreSQL',
	'power_bi':'Microsoft Power BI',
	'powerbi':'Microsoft Power BI',
	'presentations':'Public Speaking',
	'problem_solving':'Problem Solving',
	'problem-solving':'Problem Solving',
	'project_management':'Project Management',
	'prometheus':'Monitoring',
	'public_speaking':'Public Speaking',
	'pull_request':'Git',
	'pyspark':'Apache Spark',
	'python':'Python',
	'pytorch':'Machine Learning',
	'query':'Databases',
	'query_optimisation':'Databases',
	'query_optimization':'Databases',
	'rabbit':'Rabbit MQ',
	'react':'React.js',
	'reactjs':'React.js',
	'redis':'Redis',
	'relational':'Databases',
	'rest':'REST APIs',
	'restful':'REST APIs',
	'RNN':'Machine Learning',
	's3':'Amazon S3',
	'sap_data_services':'SAP',
	'scala':'Scala',
	'scrum':'Agile Methodologies',
	'snowflake':'Databases',
	'software_development':'Software Development',
	'spark':'Apache Spark',
	'speaking':'Public Speaking',
	'spring':'Spring Framework',
	'spring_boot':'Spring Framework',
	'spring_boot':'Spring Framework',
	'sql':'SQL',
	'sql_server':'Microsoft SQL Server',
	'sql_server_integration_services':'SQL Server Integration Services (SSIS)',
	'sql_server_reporting_services':'SQL Server Reporting Services (SSRS)',
	'ssis':'SQL Server Integration Services (SSIS)',
	'ssrs':'SQL Server Reporting Services (SSRS)',
	'star_schema':'Data Warehousing',
	'streaming':'Streaming Data',
	'streamsets':'StreamSets',
	'structures':'Data Structures',
	't-sql':'Microsoft SQL Server',
	'tableau':'Tableau',
	'tensorflow':'TensorFlow',
	'terraform':'DevOps',
	'transformation':'Extract, Transform, Load (ETL)',
	'transformations':'Extract, Transform, Load (ETL)',
	'transforming':'Extract, Transform, Load (ETL)',
	'tsql':'Microsoft SQL Server',
	'typescript':'JavaScript',
	'uat':'Testing',
	'unit_testing':'Testing',
	'unix':'Linux',
	'user_aceptance_testing':'Testing',
	'visualisation':'Data Visualization',
	'xml':'REST APIs'
}